# Starter pipeline
# Start with a minimal pipeline that you can customize to build and deploy your code.
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml

name: $(Version.Major).$(Version.Minor).$(Rev:.r)

trigger:
  batch: true
  branches:
    include:
    - master

variables:
- name : 'system.debug'
  value: 'true'

pool:
  vmImage: 'ubuntu-latest'

stages:
  - stage: "Build_Project"
    jobs:
      - job: 'CI_Build'
        steps:
        - task: Assembly-Info-NetCore@2
          displayName: 'Set assembly version'
          inputs:
            Path: '$(Build.SourcesDirectory)'
            FileNames: '**/*.csproj'
            InsertAttributes: false
            FileEncoding: 'auto'
            WriteBOM: false
            PackageId: 'CodeCube.FluentValidation'
            Authors: 'Rob Lohmann'
            Company: 'Rob Lohmann'
            Copyright: 'Copyright 2020 - Rob Lohmann'
            VersionNumber: '$(Build.BuildNumber)'
            FileVersionNumber: '$(Build.BuildNumber)'
            InformationalVersion: '$(Build.BuildNumber)'
            PackageVersion: '$(Build.BuildNumber)'
            LogLevel: 'verbose'
            FailOnWarning: false
            DisableTelemetry: false

        - task: DotNetCoreCLI@2
          displayName: 'Restore NuGet Packages'
          inputs:
            command: 'restore'
            projects: '**/*.csproj'
            feedsToUse: 'select'

        - task: DotNetCoreCLI@2
          displayName: 'Build Project'
          inputs:
            command: 'build'
            projects: '**/*.csproj'
            arguments: '-c Release'

        - task: DotNetCoreCLI@2
          displayName: 'Run Unit Tests'
          inputs:
            command: 'test'
            projects: |
              **/*.Test.csproj
              **/*.Tests.csproj
            arguments: '-c Release'

        - task: DotNetCoreCLI@2
          displayName: 'NuGet Pack'
          inputs:
            command: 'pack'
            packagesToPack: '**/*.csproj'
            versioningScheme: 'byBuildNumber'
        
        - task: PublishBuildArtifacts@1
          displayName: 'Publish Artifact'

  - stage: "Publish_NuGet"
    dependsOn: "Build_Project"
    jobs:
    - job: 'CD_NuGet'
      steps:
        # - task: NuGetCommand@2
        #   displayName: 'Push NuGet Package'
        #   inputs:
        #     command: 'push'
        #     packagesToPush: '$(System.DefaultWorkingDirectory)/CodeCube.FluentValidation/drop/*.nupkg;!$(Build.ArtifactStagingDirectory)/**/*.symbols.nupkg'
        #     nuGetFeedType: 'external'
        #     publishFeedCredentials: 'nuget.org'

        - task: NuGetCommand@2
          displayName: 'Push NuGet Package'
          inputs:
            command: push
            packagesToPush: '$(System.DefaultWorkingDirectory)/CodeCube.FluentValidation/drop/*.nupkg'
            nuGetFeedType: external
            publishFeedCredentials: nuget.org
